import { ScanResult } from '../types';

export function exportReportAsJson(scan: ScanResult): void {
  const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(scan, null, 2));
  const downloadAnchor = document.createElement('a');
  downloadAnchor.setAttribute("href", dataStr);
  downloadAnchor.setAttribute("download", `PhishGuard-Report-${scan.id}.json`);
  document.body.appendChild(downloadAnchor);
  downloadAnchor.click();
  downloadAnchor.remove();
}

export function exportReportAsText(scan: ScanResult): void {
  const textContent = `===============================================================
PHISHGUARD AI - THREAT INTELLIGENCE INCIDENT REPORT
Project: Smart India Hackathon Prototype
Tagline: "Detect Phishing Before It Detects You"
===============================================================

THREAT ID:          ${scan.id}
TIMESTAMP:          ${scan.timestamp}
CHANNEL:            ${scan.channel.toUpperCase()}
TARGET INPUT:       ${scan.targetInput}
CLASSIFICATION:     ${scan.classification}
RISK SCORE:         ${scan.riskScore} / 100
MODEL CONFIDENCE:   ${(scan.confidence * 100).toFixed(1)}%
PREVENTION STATUS:  ${scan.preventionStatus}
ENGINE VERSION:     ${scan.modelVersion}
ANALYSIS LATENCY:   ${scan.executionTimeMs}ms

---------------------------------------------------------------
EXPLAINABLE THREAT REASONS:
---------------------------------------------------------------
${scan.reasons.map((r, i) => `${i + 1}. [${r.severity.toUpperCase()}] ${r.title} (${r.category})\n   -> ${r.description}`).join('\n\n')}

---------------------------------------------------------------
RECOMMENDED DEFENSIVE ACTIONS:
---------------------------------------------------------------
${scan.recommendedActions.map((a, i) => `${i + 1}. ${a}`).join('\n')}

===============================================================
DISCLAIMER:
This report is generated by PhishGuard AI probabilistic risk assessment models.
Never disclose credentials, OTPs, or banking PINs to unauthorized parties.
===============================================================
`;

  const blob = new Blob([textContent], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `PhishGuard-Report-${scan.id}.txt`;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}
